### ISSUE TITLE
iOSのUnitPluginがビルドできない

### ISSUE THREAD

**Issue by 24kwakahana** [ngigroup-developer/AdStirUnityPlugin#1]
AdstirAdsSdkiOS-2.3.0のiOSライブラリは、"libAdstirAds-AdMobMediation.a" になった。
しかし、build.sh には "libAdstirWebView.a" をコピーするよう記述されており、
iOS用のUnityPackageがビルドできない。

**Comment by 0tarof** [comment]
お問い合わせ頂きました件につきましては、本日修正版をpushしております。
お手数をお掛けいたしますが、再度ご確認のほどお願い致します。

また、libAdstirAds-AdMobMediation.aは、AdMob Mediationをご利用いただくためのファイルですので、
UnityPluginでは使用しません。

その他何か問題がございましたら、ご連絡くださいませ。

**Comment by 24kwakahana** [comment]
早速の返答、ありがとうございます。

最新版を取得して試してみました。 iOS版の「 "libAdstirWebView.a" をコピーするよう記述」が修正されていました。ありがとうございました。しかし、上記処理のあと、UnityPackageをビルドするはずですが、ビルドエラーになりました。

以下は build/build.log の内容です。

> Rebuilding Library because the asset database could not be found!
> Assets/Plugins/AdstirPlugin.cs(34,40): error CS0103: The name `SPOT' does not exist in the current context
> Assets/Plugins/AdstirPlugin.cs(34,22): error CS1502: The best overloaded method match for`AdstirPlugin.ShowAd(string, int, int, int, int, int)' has some invalid arguments
> Assets/Plugins/AdstirPlugin.cs(34,22): error CS1503: Argument `#2' cannot convert`object' expression to type `int'
> Scripts have compiler errors.
> **_Thread 'UnityLookForNewInputDevices' is still running!**_
> **_Thread was not cleaned up!**_

というわけで、いまだUnityPackageを生成できておりません。なにか不手際などありましたら、ご指摘ください。

**Comment by 24kwakahana** [comment]
AdstirPlugin.csの文字コードが Shift-JIS になっていました。これが原因かもしれない。

**Comment by 0tarof** [comment]
AdstirPlugin.csにつきまして、一部コメントアウトされていない行(34行目)がございましたので、修正してpushいたしました。
お知らせ頂きありがとうございました！

また、AdstirPlugin.csのファイルがShift-JISと判定されてしまうのは、マルチバイト文字が一文字も使われていないからと思われます。
今回の事象とは関係ございません。

**Comment by 24kwakahana** [comment]
ンゴオオオオオオ＞一部コメントアウトされていない行(34行目)がございました

**Comment by 24kwakahana** [comment]
ビルドできました！ありがとうございました。Read.meに未記述でつまずいた事を書いておきます。

"android update project -p ." の行でエラーが発生した場合、
"android list target" をシェルで実行すればインストールされた androidSDK のターゲットが表示されます。
例えば、 "android-18" だった場合、以下のように build.sh を変更してください。
"android update project -p . --target android-18"

**Comment by 24kwakahana** [comment]
解決したのでCloseお願いします。

**Comment by 0tarof** [comment]
ビルドできましたようで何よりです。
ご報告ありがとうございました。

また、頂いた内容につきましては、記載方法を含めまして検討させて頂きます。
今後とも、よろしくお願い致します。
